//! `charm shell` - the SSH forced-command entry point.
//!
//! sshd runs this instead of a login shell for the `charm` user, with the
//! client's requested command in `$SSH_ORIGINAL_COMMAND`. We accept only git's
//! pack commands, lazily create the bare repo + `post-receive` hook, then exec
//! the real git command. Anything else is rejected - an authorized key can push
//! code but cannot get a shell.

use anyhow::{anyhow, bail, Context, Result};
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::os::unix::process::CommandExt;
use std::path::Path;
use std::process::{Command, Stdio};

use crate::paths;

const ALLOWED: [&str; 3] = ["git-receive-pack", "git-upload-pack", "git-upload-archive"];

pub fn run() -> Result<()> {
    let original = std::env::var("SSH_ORIGINAL_COMMAND").unwrap_or_default();
    if original.is_empty() {
        // An interactive SSH session (no git command) opens the console.
        return crate::tui::run();
    }

    let parts = shell_words::split(&original).context("parsing SSH_ORIGINAL_COMMAND")?;
    let verb = parts.first().context("empty command")?;
    if !ALLOWED.contains(&verb.as_str()) {
        bail!("charm: '{verb}' is not allowed");
    }
    let raw = parts.get(1).context("no repository specified")?;
    let app = normalize_app(raw)?;
    let repo = format!("{}/{}.git", paths::repos(), app);

    if verb == "git-receive-pack" {
        ensure_repo(&app, &repo)?;
    } else if !Path::new(&repo).exists() {
        bail!("charm: no such app '{app}'");
    }

    // `git-receive-pack` → `git receive-pack`: robust regardless of where the
    // standalone wrappers live on a given distro.
    let sub = verb.strip_prefix("git-").unwrap_or(verb);
    let err = Command::new("git").arg(sub).arg(&repo).exec();
    Err(anyhow!("failed to exec `git {sub}`: {err}"))
}

/// Turn a pushed path (`'/demo'`, `'org/app.git'`) into a clean app id.
fn normalize_app(raw: &str) -> Result<String> {
    let s = raw
        .trim()
        .trim_start_matches('/')
        .trim_start_matches("~/")
        .trim_end_matches('/')
        .trim_end_matches(".git");
    if s.is_empty() {
        bail!("charm: empty app name");
    }
    if !s
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '/'))
    {
        bail!("charm: invalid app name '{s}'");
    }
    Ok(s.to_string())
}

fn ensure_repo(app: &str, repo: &str) -> Result<()> {
    if !Path::new(repo).exists() {
        // stdout IS the git pack-protocol channel - git init's "Initialized…"
        // message would corrupt it, so silence it.
        let status = Command::new("git")
            .args(["init", "--bare", repo])
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status()
            .context("git init --bare")?;
        if !status.success() {
            bail!("charm: failed to create repo for '{app}'");
        }
    }
    write_hook(app, repo)
}

fn write_hook(app: &str, repo: &str) -> Result<()> {
    let hook = format!("{repo}/hooks/post-receive");
    // post-receive gets `<old> <new> <ref>` per updated ref on stdin; pass each
    // to `charm deploy`, which decides which refs are deployable.
    let script = format!(
        "#!/bin/sh\n# generated by charm - do not edit\n\
         while read -r old new ref; do\n  \
         {bin} deploy {app} \"{repo}\" \"$ref\" \"$new\" || exit 1\n\
         done\n",
        bin = paths::BIN,
        app = app,
        repo = repo,
    );
    fs::write(&hook, script).with_context(|| format!("writing {hook}"))?;
    fs::set_permissions(&hook, fs::Permissions::from_mode(0o755))?;
    Ok(())
}
